import { Platform, StyleSheet } from "react-native";

export default StyleSheet.create({
    mainContainer: { paddingTop: Platform.OS === "android" ? 0 : 0, backgroundColor: "white" },
  mainContainerDark: { paddingTop: Platform.OS === "android" ? 0 : 0, backgroundColor: "black" },
  txtAbout: { marginVertical: 10, color: "blue", fontSize: 24, fontWeight: "bold", textAlign: "center" },
  txtAboutContent: { marginVertical: 10, color: "black", fontSize: 18, paddingHorizontal: "5%", textAlign: "center" },
  txtAboutContentDark: { marginVertical: 10, color: "white", fontSize: 18, paddingHorizontal: "5%", textAlign: "center" },
  aboutImage: { marginBottom: 20, width: "70%", height: "10%", alignSelf: "center" },
  txtMession: { marginVertical: 10, color: "blue", fontSize: 24, fontWeight: "bold", textAlign: "center" },
  txtMessionContent: { marginVertical: 10, color: "black", fontSize: 18, paddingHorizontal: "5%", textAlign: "center" },
  txtMessionContentDark: { marginVertical: 10, color: "white", fontSize: 18, paddingHorizontal: "5%", textAlign: "center" },
  dropDownMenu: { marginVertical: 10, width: "90%", alignSelf: "center", borderColor: "black", borderWidth: 2, borderRadius: 5 },
  dropDownMenuDark: { marginVertical: 10, width: "90%", alignSelf: "center", borderColor: "white", borderWidth: 2, borderRadius: 5 },
  dropDownMenu2: { color: "black" },
  dropDownMenu2Dark: { color: "red" },
  map: { width: "90%", height: 500, alignSelf: "center", marginBottom: 10 },
  Icons: { color: "red", alignSelf: "center" },
  labelsForContact: { marginVertical: 10, color: "black", fontSize: 17, paddingHorizontal: "5%", textAlign: "center" },
  labelsForContactDark: { marginVertical: 10, color: "white", fontSize: 17, paddingHorizontal: "5%", textAlign: "center" },
  txtInputs: {
    color: "black",
    backgroundColor: "white",
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  txtInputsDark: {
    color: "white",
    backgroundColor: "black",
    borderColor: "white",
    height: 40,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  txtInputsMessage: {
    color: "black",
    backgroundColor: "white",
    height: 100,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  txtInputsMessageDark: {
    color: "white",
    backgroundColor: "black",
    borderColor: "white",
    height: 100,
    margin: 12,
    borderWidth: 1,
    padding: 10,
  },
  shadowBox: {
    shadowOffset: { width: 0, height: 4 },
    shadowColor: "gray",
    shadowOpacity: 0.17,
    shadowRadius: 3.05,
    elevation: 4,
    width: "100%",
    backfaceVisibility: "white",
    borderRadius: 8,
    paddingVertical: 45,
    paddingHorizontal: 25,
    marginVertical: 10,
  },
  button: { backgroundColor: "blue", textAlign: "center", alignSelf: "center", borderRadius: 5, width: "40%", height: "10%", marginTop: 50 },
  btnTxt: { textAlign: "center", padding: "15%", height: "100%", color: "white", fontSize: 18 },
});